const express = require('express')
const route = express.Router()
const supplierController = require('../controllers/supplier.C')
route.get('/', supplierController.productManage)
route.get('/:supID/order', supplierController.orderManage)
route.get('/:supID/order/update', supplierController.updateStatus)
route.get('/:supID/detail', supplierController.productDetail)
route.post('/:supID/detail', supplierController.updateProduct)
route.get('/:supID/delete', supplierController.deleteProduct)
route.get('/:supID/add', supplierController.addProductView)
route.post('/:supID/add', supplierController.addProduct)
route.post('/:supID/discount', supplierController.discountPrice)
route.post('/:supID/increase-price', supplierController.increasePrice)
route.get('/:supID/contracts', supplierController.viewContracts)
route.post('/:supID/contracts/add', supplierController.addContract)
module.exports = route